### ISSUE TITLE
Use `Cargo.lock` for top level project

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/jsonrpc#118]
Currently some upstream changes can break our builds, see #117

**Comment by NikVolf** [comment]
we can end up crashing projects that use our lib, then

if our `dependencyA` in our Cargo.lock will be behind `dependencyA` in the Cargo.lock of parity, for example

this should actually be managed by semver convention where minor versions changes never lead to the breaking changes

**Comment by tomusdrw** [comment]
But we actually never reference the meta project, just the subprojects that don't have `Cargo.lock` files. Do you think the meta one will be taken into account?

**Comment by NikVolf** [comment]
No, but this is the problem
Project that references our lib will never take in account any of our Cargo.lock -s, root or not, but we will during compilation if choose to leave it. That can lead to breaking changes in other projects we will not see on the CI.
