### ISSUE TITLE
Update to serde 1.0

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/jsonrpc#123]
https://github.com/serde-rs/serde/releases/tag/v1.0.0

- [x] Migrate to serde 1.0
- [ ] Zero-copy deserialization (might require a lot of changes with lifetimes)

**Comment by Marwes** [comment]
Any chance of a release with serde 1.0.0? (even without the zero-copy part)

**Comment by tomusdrw** [comment]
We're working our way towards releasing 7.0.0. Just some minor stuff left and battle testing. Expect a new version within a month. For now you can reference the git version.

**Comment by debris** [comment]
@tomusdrw I don't see a point to implement zero-copy deserialization for jsonrpc crates in nearest future. Should we close this issue?
