### ISSUE TITLE
Macros parameter limitation

### ISSUE THREAD

**Issue by mmacedoeu** [paritytech/jsonrpc#127]
Looks like there is a limitation to the number of parameters you can define in build_rpc_trait! macros
So I am looking for a way to circumvent this shortcoming with a generic parameter I could parse myself inside impl but couldn't realize so far, tried this:

```rust
use jsonrpc_core::{Error, Params};
use jsonrpc_core::futures::BoxFuture;
use std::collections::BTreeMap;
use serde_json::{self,Value};

build_rpc_trait! {
	/// RPC Interface.
	pub trait Faucet {
    type Metadata;
		#[rpc(meta, name = "faucet_new")]
		fn faucet_new(&self, Self::Metadata, BTreeMap<String, Value>) -> BoxFuture<BTreeMap<String, String>, Error>;
	}
}
```  

Or 

```rust
use jsonrpc_core::{Error, Params};
use jsonrpc_core::futures::BoxFuture;
use std::collections::BTreeMap;
use serde_json::{self,Value};

build_rpc_trait! {
	/// RPC Interface.
	pub trait Faucet {
    type Metadata;
		#[rpc(meta, name = "faucet_new")]
		fn faucet_new(&self, Self::Metadata, Value) -> BoxFuture<BTreeMap<String, String>, Error>;
	}
}
```  

But I am getting error code -32601 "Method not found", What can be done to receive a serialized Json Object over RPC ?

**Comment by tomusdrw** [comment]
"Method not found" sounds suspicious, you should be able to easily receive a `BTreeMap<String, Value>` (otherwise the code wouldn't compile). You can also create a structure and use `serde_derive` to implement `Deserializable` trait, and just use that struct as one of the parameters.

I've also updated the example in macros to be more complete, have a look at the code in #128

**Comment by mmacedoeu** [comment]
Sorry, the correct error is:

`{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: invalid type: map, expected a tuple of size 1."},"id":1}`

**Comment by tomusdrw** [comment]
So instead of doing `"params":{"mymap":1}` please try `"params":[{"mymap":1}]`.
Macros always expect the parameters to be passed in as an array.

**Comment by mmacedoeu** [comment]
That's it ! Working now :)
