### ISSUE TITLE
Don't consume MetaIoHandler until all error handling is done

### ISSUE THREAD

**Issue by faern** [paritytech/jsonrpc#141]
I have a use case where I want to bind the server to a local port and I don't really care what the port is, I just need to know it when done setting up. So I have a loop where I iterate from port X to Y and try each until `ServerBuilder::start` returns success or I'm all out of options.

The problem is that `ServerBuilder::new` consumes my handler. So I have to create a new one for each try. This severely limits how I can implement my handlers and force me to either put stuff behind clonable `Arc<Mutex<...>>`es or some other weird solution.

Is this a use case you would like to support? If so I have two ideas how to solve it:
* The error in `ServerBuilder::start` can contain my handler so I can extract it from a failed try.
* `ServerBuilder::new` does not take my handler. Instead the API is rewritten so the handler is given after it is known that the server can be created. To do this `ServerBuilder::start` could return a `Result<IntermediateServerBuilder>` with one method: `start(handler) -> Server`.

**Comment by tomusdrw** [comment]
Binding to port number `0` should cover your use case, you can get assigned port from `Server` (I think it's not implemented for WS transport, because that feature is missing upstream).
Which transport do you use?

**Comment by faern** [comment]
Oh. Stupid me. How did I not think about that... Thanks

However, I do use websocket at the moment so it won't help me right away. Maybe I can help patch it to support this though? So this feature is missing from the `ws` crate? And after adding it there it should likely work for this ws server implementation?

**Comment by tomusdrw** [comment]
Correct. I have a PR pending that lays some ground for this, but don't have enough time to finish it: https://github.com/housleyjk/ws-rs/pull/133
Feel free to add this feature there.

**Comment by faern** [comment]
I tried it out just now and binding to port `0` does bind to a random port number, as it should. The problem is that `server.addr()` still reports port 0, and not the port it was actually assigned. I see, will see if I find time to help fix that.

**Comment by faern** [comment]
@tomusdrw Your PR seems a bit outdated with regard to master. I'll see if I can fix it directly on upstream and then maybe you can adapt your code. Would be nice if `jsonrpc-ws-server` could use `ws` directly from crates.io. Anything else stopping that?

**Comment by tomusdrw** [comment]
To use `ws` from crates.io was the exact purpose of that PR, the critical thing is that we need arbitrary responses to handshake.

**Comment by faern** [comment]
This will be solved by #146
