### ISSUE TITLE
Insert newlines after responses?

### ISSUE THREAD

**Issue by canndrew** [paritytech/jsonrpc#144]
Hi. I'm trying to use this library to communicate between python and rust over an IPC socket. I want to use a single connection to make multiple consecutive RPC calls. The problem is, I don't have a way to parse a single response from the RPC server. [This stackoverflow question](https://stackoverflow.com/questions/6886283/how-i-can-i-lazily-read-multiple-json-objects-from-a-file-stream-in-python) describes the exact issue I'm having.

The suggested answer there is that the server should be delimiting responses with a newline so that they can be parsed individually. Failing that, I would have to write my own python JSON parser.

So, it is possible to modify this library so that it adds a `'\n'` after each JSON response? Or would that break things for other users?

**Comment by NikVolf** [comment]
Both TCP/IP and IPC servers add `'\n'` after each response
HTTP and WebSockets obviously don't, because they don't need to deal with framing.

What protocol you are referring?

**Comment by tomusdrw** [comment]
@canndrew Let us also know which `jsonrpc` version you're using.

**Comment by canndrew** [comment]
Sorry, it's probably been fixed in a newer version. I'm using 6.0.0 over IPC. On my local copy I made `write_response` add a newline to the end of the returned string and that fixed my problems.

**Comment by NikVolf** [comment]
@canndrew yeah, i was mentioning the latest master
indeed, 6.0.0 does not produce new lines between responses

so if you need them badly, just reference crate from github directly to use the latest master (since current 7.0.0 version was never published in crates.io for now)
