### ISSUE TITLE
Ending character in the protocol

### ISSUE THREAD

**Issue by adam0z** [paritytech/jsonrpc#162]
Hello, I have done a small research looking for a Rust RPC library and yours looks mature and pro.
I successfully run a Rust server and I tried to connect using Python client - to make it clear I used this [code](https://github.com/Orhideous/json-rpc-3/blob/master/examples/tcp/proxy.py).

The client could not receive any byte. As you can see in the [code](https://github.com/Orhideous/json-rpc-3/blob/master/examples/tcp/tools.py), the client sends '\x00' byte at the end of a message and looks forward for the same character at the end of the response. The client will successfully receive the data if we change the ending character to '\n'.

Is it intented behavior? Should the message and the response end with newline character?

**Comment by tomusdrw** [comment]
The JSON-RPC protocol doesn't specify how to delimit the messages. For transports like HTTP or WebSockets this is not really a problem, cause the requests are separate on transport level.
For IPC (I suspect that's the transport you're referring to) it' a bit more complicated, the delimiting character varies between implementation. We're using `\n` (but also supporting requests that are not delimited at all) and from what you say it seem that Python uses `\x00`.
I suppose we could make the delimiting character configurable to support that other implementations.

**Comment by adam0z** [comment]
Thanks for your response. I'm using and I was referring to TCP transport. I have found a [discussion ](https://github.com/ethereum/go-ethereum/issues/3702) and `\n` as message separator looks like a good choice.
Are you going to make the separator configurable in the future?

**Comment by NikVolf** [comment]
@adam0z 
Yep, we will update shortly, probably it will be configurable including no separator at all

**Comment by NikVolf** [comment]
@adam0z 
see https://paritytech.github.io/jsonrpc/jsonrpc_tcp_server/struct.ServerBuilder.html#method.request_separators

to configure (latest master)
