### ISSUE TITLE
global struct to handlers / add r2d2 diesel connection pooling to Metadata

### ISSUE THREAD

**Issue by greenpdx** [paritytech/jsonrpc#220]
I got diesel working with jsonrpc_http_server, but each time I have to open and close a connection(slow). Now I am trying to r2d2 connection pooling.  r2d2 has it own thread safety code.  The handler only has two parameters Params and Meta.  I am trying to add a r2d2 connection pool to the Meta structure. And I am chasing my tail because of lifetimes and borrows.

In main I create a connection pool the I try to add it to the Metadata.   
First: there is no default for the pool so I wrap it in an Option<DieselPool>
      DieselPool does support clone()

When I try to use references & then I get into life time hell.  I guess my overall question is how do I pass a reference to a "main variable"/ global to a RpcMethod?

```
pub type DieselPool = r2d2::Pool<ConnectionManager<PgConnection>>;
pub type DieselConnection = r2d2::PooledConnection<ConnectionManager<PgConnection>>;

#[derive(Clone, Default)]
pub struct DieselMidWare {
    pool: Option<DieselPool> // I would like to use just &DieselPool, the life time hell
}
impl DieselMidWare {
	pub fn new (logger: &Logger) -> DieselMidWare{
		let logger = logger.new(o!("module" => "DieselMidWare"));

		let database_url = env::var("DATABASE_URL").expect("DATABASE_URL must be set");

		let config = r2d2::Config::default();
		let manager = ConnectionManager::<PgConnection>::new(database_url);
		let pool = r2d2::Pool::new(config, manager).expect("Failed to create diesel pool.");

		info!(logger, "Diesel pool created");

		DieselMidWare {pool: Some(pool)}
	}

    pub fn get(&self) -> Option<DieselConnection> {
        let pool = &self.pool;
        Some(self.pool.unwrap().get().unwrap())
    }
}
```
I then add it to the Metadata
```
#[derive(Clone, Default)]
struct Meta {
    remote: Option<SocketAddr>,
//    bob: (Method, Uri, HttpVersion, Headers, Body),
    methd: Method,
    uri: Uri,
    hdrs: Headers,
    dbpool: DieselMidWare,
//    path: String,
}
impl Metadata for Meta {}

impl fmt::Debug for Meta {
    fn fmt(&self,f: &mut Formatter) -> fmt::Result {
        let pgstr = "PG".to_string();
        write!(f, "{:?} {:?} {:?} {:?} {:?}", self.remote, self.methd, self.uri, self.hdrs, pgstr)
    }
}
#[derive(Default)]
struct MyMiddleware(AtomicUsize);
impl Middleware<Meta> for MyMiddleware {
	type Future = FutureResponse;

	fn on_request<F, X>(&self, request: Request, meta: Meta, next: F) -> FutureResponse where
		F: FnOnce(Request, Meta) -> X + Send,
		X: Future<Item=Option<Response>, Error=()> + Send + 'static,
	{
		let start = Instant::now();
		let request_number = self.0.fetch_add(1, atomic::Ordering::SeqCst);
		//println!("Processing request {}: {:?}, {:?}", request_number, request, meta);

		Box::new(next(request, meta).map(move |res| {
			println!("Processing took: {:?}", start.elapsed());
			res
		}))
	}
}
```
When I try to add it to the metadata I get a borrow error

```
let _server = ServerBuilder::new(io)
//        .threads(3)
        .rest_api(RestApi::Unsecure)
        .meta_extractor(|req: &hyper::Request| {
            let methd =req.method().clone();
            let uri = req.uri().clone();
            let hdrs = req.headers().clone();
            let remote = req.remote_addr().clone();
            let dbpool = &thepool.clone();

            Meta { methd, uri, hdrs, remote, dbpool: dbpool }
        })
```

**Comment by tomusdrw** [comment]
You can only store `'static` stuff in `Metadata`.
Have you considered wrapping `DieselPool` into `Arc` to make it cloneable?

**Comment by greenpdx** [comment]
That is a little beyond my rust skills. How would that be done? what side effects would there be?

**Comment by tomusdrw** [comment]
Just checked the docs, and `r2d2::Pool` is clonable (you can even see example here: https://github.com/diesel-rs/r2d2-diesel/blob/master/examples/postgres.rs#L16)

```rust
#[derive(Clone, Default)]
struct Meta {
    remote: Option<SocketAddr>,
    methd: Method,
    uri: Uri,
    hdrs: Headers,
    dbpool: Option<DieselPool>
}
let pool = r2d2::Pool::new(config, manager).expect("Failed to create pool.");
let _server = ServerBuilder::new(io)
//        .threads(3)
        .rest_api(RestApi::Unsecure)
// you need to `move` the ownership to the closure
        .meta_extractor(move |req: &hyper::Request| {
            let methd =req.method().clone();
            let uri = req.uri().clone();
            let hdrs = req.headers().clone();
            let remote = req.remote_addr().clone();
            let dbpool = pool.clone();

            Meta { methd, uri, hdrs, remote, dbpool: Some(dbpool) }
        })
```

**Comment by greenpdx** [comment]
Thanks I will chew on this tomorrow.

**Comment by greenpdx** [comment]
Got it working with single access, will need to setup concurrent testing.

**Comment by greenpdx** [comment]
here is what I have so far. I have r2d2 and logging working. I re-factored the code and cleaned it up. I have written a Single page web app written in Vue front-end for it. I am trying to create a subproject for it because it is a totally different git repo.  
https://github.com/greenpdx/jsonrpc_diesel

Should I create a "new" for MyMiddleware and pass in logger or database  pool?
or create a Meta "new" or "default" so I do not have to  use Options?

**Comment by tomusdrw** [comment]
`Middleware` is not really neccessary, please implement `Default` for `Meta` for now and use `Option`s. There is a PR pending removing that bound: https://github.com/paritytech/jsonrpc/pull/221 so in future you will just create `Meta` in your `meta_extractor` and pass whatever you want there.
