### ISSUE TITLE
JSON-RPC client and server on the same TCP socket

### ISSUE THREAD

**Issue by gsingh93** [paritytech/jsonrpc#226]
Currently, this library allows you to start a local TCP server to listen for JSON-RPC requests and reply with responses. You cannot send requests to a client. However, there are some cases where a JSON-RPC client also acts like a server. For example, the client might make a request to a server, receive a response, and then the server might send a request to the client, and the client is expected to handle it as if it was a server. An example of this is the [stratum protocol](https://slushpool.com/help/manual/stratum-protocol#developers).

Does this library support this use case? If not, would you be open to supporting it?

**Comment by gsingh93** [comment]
Thoughts on this @tomusdrw?

**Comment by tomusdrw** [comment]
Hi @gsingh93,

There are few parts of the library:
- `core` - general data structures suitable for client and server and `IoHandler` responsible for deserializing requests, handling them and serializing the response back.
- `http`/`ws`/etc - transport implementations allowing to easily set up JSONRPC servers

So the library is more focused on JSON-RPC server part currently (we also support mentioned mechanism of notificatios with `pubsub` crate).

That said, it would be possible to use data structures from `core` to implement client and handle incoming notifications.

**Comment by neysofu** [comment]
Does anybody have a working example of blending the built-in server with a custom client as suggested by @tomusdrw?

**Comment by tomusdrw** [comment]
Hi @neysofu, have a look at https://github.com/mullvad/jsonrpc-client-rs

**Comment by tomusdrw** [comment]
Seems resolved, please reopen if it's not the case.
