### ISSUE TITLE
crates.io releases

### ISSUE THREAD

**Issue by kpcyrd** [paritytech/jsonrpc#231]
I've noticed some crates seem to be out of date:

https://crates.io/crates/jsonrpc-ipc-server is on 6.0.0, which was released in february 2017. Could you consider pushing a new release? :)

**Comment by ivanovaleksey** [comment]
Hello, to avoid creating new issue I am writing here. 
It is not about _jsonrpc-ipc-sever_, but issue's subject is relevant.
I would like to use _jsonrpc-core_ for production application.

Is this project still alive and maintained? It definitely looks like it is but I just want to ensure.
Thanks.

**Comment by tomusdrw** [comment]
@kpcyrd Current version of IPC server supports windows and because of that uses some deps hosted only on github. We need to review them and publish to crates.io.

**Comment by ivanovaleksey** [comment]
@tomusdrw by "alive" I mean that if someone would have a problem he could get some help via GitHub issues. By "maintained" I mean those issues could be fixed or one could get some guidance to create a PR to fix it by himself. Something like that...

**Comment by tomusdrw** [comment]
@ivanovaleksey Both true then!

**Comment by tomusdrw** [comment]
As of version 10.0 all versions should be on crates.io.
