### ISSUE TITLE
Client examples

### ISSUE THREAD

**Issue by kpcyrd** [paritytech/jsonrpc#232]
I'm having trouble finding client examples, could you point me in the right direction (and maybe add some of them to examples/)? Thanks! :)

**Comment by niclashoyer** [comment]
I just had a quick look, too. There seems to be just minimal support. All the examples use this form with literal strings:

```
let request = r#"{"jsonrpc": "2.0", "method": "say_hello", "params": [42, 23], "id": 1}"#;
let response = r#"{"jsonrpc":"2.0","result":"Hello World!","id":1}"#;

assert_eq!(io.handle_request(request).wait().unwrap(), Some(response.to_string()))
```

So it seems that aside from that there is no request builder, which would be very nice to have. As for now it seems that we'll have to build request strings by ourselves @tomusdrw ?

**Comment by tomusdrw** [comment]
You can use `jsonrpc_core` types to build a request and serialize it with `serde_json`. Then such request needs to be pushed through a transport connected to the RPC server (http/tcp/ws/ipc).

Building a client library is currently beyond the scope of this library. Please have a look at https://github.com/mullvad/jsonrpc-client-rs

If you only need to generate requests for tests (`io.handle_request(...)`) consider https://docs.rs/jsonrpc-test/8.0.0/jsonrpc_test/

**Comment by niclashoyer** [comment]
Oh great, [jsonrpc-client-rs](https://github.com/mullvad/jsonrpc-client-rs) looks promising, thanks. Maybe you should link to that in the readme 😃

**Comment by tomusdrw** [comment]
@niclashoyer happy to accept PR with updated readme :)
