### ISSUE TITLE
no method named `eq_ignore_ascii_case

### ISSUE THREAD

**Issue by freshonline** [paritytech/jsonrpc#236]
error[E0599]: no method named `eq_ignore_ascii_case` found for type `std::string::String` in the current scope
  --> /home/testnet/.cargo/git/checkouts/jsonrpc-22a65938f7d26b63/786f3e1/server-utils/src/matcher.rs:31:19
   |
31 |                    None => self.1.eq_ignore_ascii_case(s),
   |                                   ^^^^^^^^^^^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           candidate #1: `use std::ascii::AsciiExt;`

error: aborting due to previous error

error: Could not compile `jsonrpc-server-utils`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by NikVolf** [comment]
Please upgrade to Rust 1.23
`rustup update stable`

**Comment by schilpr** [comment]
Getting the same error.. and I'm on rustc 1.24.1, the 2018-02-27 release.

**Comment by debris** [comment]
@schilpr are you sure that you don't have `rustup override` set for current build directory? `eq_ignore_ascii_case` has been [stabilized on rust 1.23](https://doc.rust-lang.org/src/alloc/str.rs.html#2166)
