### ISSUE TITLE
Failing to build parity

### ISSUE THREAD

**Issue by AyushyaChitransh** [paritytech/jsonrpc#237]
Parity build using `cargo build --release` fails with following error:

```
error[E0599]: no method named `eq_ignore_ascii_case` found for type `std::string::String` in the current scope
  --> /Users/ayushyachitransh/.cargo/git/checkouts/jsonrpc-22a65938f7d26b63/786f3e1/server-utils/src/matcher.rs:31:19
   |
31 |    None => self.1.eq_ignore_ascii_case(s),
   |                   ^^^^^^^^^^^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           candidate #1: `use std::ascii::AsciiExt;`
```

Before building, it has been ensured that I have the latest code from the repository of paritytech/parity and the crate being used is the latest available on master of `paritytech/jsonrpc`

**Comment by tomusdrw** [comment]
Please update your compiler. The trait is no longer necessary from 1.23 onwards (and 1.24 has been stabilized couple of days ago)
