### ISSUE TITLE
Custom errors handling

### ISSUE THREAD

**Issue by ivanovaleksey** [paritytech/jsonrpc#240]
Hello, thanks for the great libraries!

I use `jsonrpc-core` to build MQTT-based application.
The application implements CRUD operation, I use `diesel` and `serde_json` for that.
Right now I don't have any application specific errors, and errors mostly come from `diesel` and `serde_json`.
In the future there would be application specific errors too, e.g. for dealing with permissions.
I am not very well with Rust errors (I hope I will learn it some day).

So, the gist is looking like
```rust
pub fn build_server() -> Server {
    let mut io = MetaIoHandler::default();

    io.add_method("ping", |params: Params| {
        let _msg: Message = params.parse()?;
        Ok(to_value(Message::Pong).unwrap())
    });

    io.add_method("room.create", room_create);
    // More CRUD methods here

    io
}

fn room_create(params: Params) -> jsonrpc_core::Result<Value> {
    let req: room::CreateRequest = params.parse()?;
    let conn = establish_connection();
    let room: models::Room = diesel::insert_into(rooms::table)
        .values(&req.data)
        .get_result(&conn)
        .unwrap();

    let resp = room::CreateResponse::new(&room);
    Ok(to_value(resp).unwrap())
}
```

As you can see there are few `unwrap` here which I want to avoid.
The problem is I don't know how to handle these errors nicely.
If I use `?` instead of `unwrap` I get errors:
```
the trait `std::convert::From<diesel::result::Error>` is not implemented for `jsonrpc_core::Error`
the trait `std::convert::From<serde_json::Error>` is not implemented for `jsonrpc_core::Error`
```

If I return `Result<Value, MyError>` (where `MyError` is defined with `error_chain`) I get
```
type mismatch resolving `<jsonrpc_core::<unnamed>::FutureResult<jsonrpc_core::Value, errors::Error> as jsonrpc_core::<unnamed>::Future>::Error == jsonrpc_core::Error`
```
I have looked at [`RpcMethodSimple` implementation ](https://github.com/paritytech/jsonrpc/blob/master/core/src/calls.rs#L59-L68), future's error can be only of type `jsonrpc_core::Error` which in turn means that `Result` can be only of this type too (which it stated by error message).

What approach should I use for this? I mean how to solve it right both from Rust and JSON-RPC specification points of view?

There is `ErrorCode::ServerError` variant, should I use it to wrap all my errors?
Something like `impl From<diesel::result::Error> for jsonrpc_core::Error`?

[JSON-RPC specification](http://www.jsonrpc.org/specification#error_object) says

-32000 to -32099 | Server error | Reserved for implementation-defined server-errors.
-- | -- | --

> The remainder of the space is available for application defined errors.

It seems to me that those errors are totally "application defined" but I don't understand how I can manage them.

Could you please give me an advice?
Thank you.

P. S.
I feel like there must be `ErrorCode::CustomError` but I guess it is intentionally not implemented.
It makes me think there must be another way.

**Comment by tomusdrw** [comment]
Hi @ivanovaleksey.
Currently we don't support custom error types in `jsonrpc-core`. So you need to manually convert your error to `jsonrpc_core::Error`.

Which is not that difficult if you are using `?` operator, although requires all errors to implement `Into<jsonrpc_core::Error>`.

Example (didn't test if it compiles):
```rust
extern crate jsonrpc_core as rpc;
enum MyErrorType {
  A,
  B,
  Serde(serde::Error),
}
impl From<MyErrorType> for rpc::Error {
 fn from(...) { ... }
}
impl From<serde::Error> for MyErrorType {
 ...
}

let mut io = MetaIoHandler::default();
io.add_method("ping", |params: Params| {
     let _msg: Message = params.parse()?;
     do_sth_that_returns_MyErrorType()?;

     Ok(to_value(Message::Pong).map_err(MyErrorType::Serde)?)
});
```

Also have a look at https://crates.io/crates/error_chain or https://crates.io/crates/failure crates to help you out with error definitions.


We do support custom error types in `jsonrpc-macros`. You can find an example here:
https://github.com/paritytech/jsonrpc/blob/master/macros/examples/std.rs
and a real-life example:
https://github.com/paritytech/polkadot/blob/master/substrate/rpc/src/chain/mod.rs#L35 (trait definition)
https://github.com/paritytech/polkadot/blob/master/substrate/rpc/src/chain/error.rs#L29 (custom error type conversion)

I would really recommend to try it out since it is a great help when you are developing a bit more complex RPC server.

**Comment by ivanovaleksey** [comment]
@tomusdrw thanks you for the reply and for the examples!

I am a little bit familiar with `error_chain` (you can see from the message above that I am already using it in this application). And I consider switching to `failure`.

Yes, I seem to understand that I could `impl From<MyErrorType> for rpc::Error` but what `ErrorCode` should I use? I can see _polkadot_ turns error into `rpc::ErrorCode::ServerError`.
I thought it wouldn't go well with specs what is why I hesitated.

As regards using macros, I have noticed this feature but I thought that it would difficult to start with.
I decided to start with manual implementation and then switching to macro once I get comfortable with `jsonrpc-core`. If you recommend it maybe I should think about it once again.

As far as I understand supporting custom error types is not restricted to using at all, isn't it?
The main thing is to define `impl From` and return `Result<_, MyError>`, right?

**Comment by ivanovaleksey** [comment]
I am trying to use macros. It's really very handy and powerful!
I noticed that `params` are always expected to be an Array not Object, right?
Looks like it is so because of [using a `Tuple` in expansion](https://github.com/paritytech/jsonrpc/blob/master/macros/src/auto_args.rs#L318).
So, if I have _key-value_ parameters I should wrap them with `[]` like
```json
{
    "jsonrpc": "2.0",
    "method": "create",
    "params": [{
        "data": {
            "label": "Text here"
        }
    }]
}
```

**Comment by tomusdrw** [comment]
> "ServerError for everything" is that it always has message = "Server error" .

you are free to use any message you want:
https://github.com/paritytech/parity/blob/master/rpc/src/v1/helpers/errors.rs#L100-L106

> why rpc::Error doesn't implement Error trait?

It should.

> The main thing is to define impl From and return Result<_, MyError>, right?

Yes with macros you can return any type you want, but for regular methods you are limited to returning `rpc::Error`. This is a bit pain in the ass, cause you cannot use `?` syntax for error like `serde::Error` - you need to wrap them first (that's pretty much what macros are doing, by explicitly specifying that it should be wrapped in your custom error type first and later converted to `rpc::Error`)

> So, if I have key-value parameters I should wrap them with [] like

Yes, unfortunately a limitation of macros. We could probably implement a special kind of single-parameter method that expects an object directly not within an array.

**Comment by ivanovaleksey** [comment]
> you are free to use any message you want

Indeed, don't know why I thought I can't do this.

> This is a bit pain in the ass, cause you cannot use `?` syntax

Yes, I have tried to handle errors without macros and realized that it's not so convenient. 

> `rpc::Error` should implement `Error`

Do you mean it's a place for improvement or it's already implemented and I am just missing it?
As far as I understand [here](https://github.com/paritytech/jsonrpc/blob/master/core/src/types/error.rs) must be something like `impl ::std::error::Error for Error`.

> Yes, unfortunately a limitation of macros.

I have looked at [Ethereum JSON-RPC API](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction) and noticed that `params: [{ ... }]` syntax is used here also. Maybe it is not so bad and can be considered as normal approach?

**Comment by tomusdrw** [comment]
> Do you mean it's a place for improvement or it's already implemented and I am just missing it?

Just checked and it seems missing, I don't remember if it was a conscious decision though. Technically it's not really an error but a serializable datastructure that is returned by the protocol (so it's not meant to be wrapped, but rather it's just to be returned from method implementations). @debris what do you think?

> noticed that params: [{ ... }] syntax 

Yeah, it matches more classical (not-named like in python) positional arguments to Remote Procedures.
