### ISSUE TITLE
Add notification with macro

### ISSUE THREAD

**Issue by ivanovaleksey** [paritytech/jsonrpc#252]
Hello, 

I use `build_rpc_trait` macro to construct a server.
I would like add a notification (i.e. method without `id`).

As far as I can see only `add_method` is used within the macro.
Maybe we could add support for notifications while working on #66?

**Comment by tomusdrw** [comment]
Sure, sounds good! Although I think it might be better to have it as a separate PR if possible (easier to review).

**Comment by tomusdrw** [comment]
Note that it now should be added to `jsonrpc-derive` instead of `macros`.

**Comment by ebkalderon** [comment]
Is this issue currently being worked on? I might be able to tackle this soon, if time permits.

**Comment by tomusdrw** [comment]
@ebkalderon I don't think there is anyone actively working on it, so feel free to tackle this.

**Comment by ebkalderon** [comment]
Does the generated client code in `generate_client_methods()` need to be changed to support notifications as well? There are calls to the underlying client's [`call_method()`](https://github.com/paritytech/jsonrpc/blob/44c501bc4182c7fef7d56d0efc780cd7fbb98419/derive/src/to_client.rs#L109) and [`subscribe()`](https://github.com/paritytech/jsonrpc/blob/44c501bc4182c7fef7d56d0efc780cd7fbb98419/derive/src/to_client.rs#L132) methods. Should we also add a `notify()` method to `RawClient`/`TypedClient` as well?

**Comment by ebkalderon** [comment]
@tomusdrw Pull request #454 is open and ready for review!

**Comment by ebkalderon** [comment]
Looks like the Travis CI `sccache` is poisoned and multiple open pull requests are failing CI due to linking issues.

See https://github.com/paritytech/jsonrpc/pull/454#issuecomment-512201193.

**Comment by ebkalderon** [comment]
@tomusdrw Looks like the linking issue with the `trybuild` crate is occurring again on Travis CI macOS builds. The PR itself is ready for review once more, though.

**Comment by ascjones** [comment]
@ebkalderon I'd say the client methods can be implemented in a follow up PR. See https://github.com/paritytech/jsonrpc/pull/454#discussion_r305776060
