### ISSUE TITLE
IPC leaks connections (when internally using PubSubSession)

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/jsonrpc#275]
Heyah,

investigating a [leak in IPC connections in Parity](https://github.com/paritytech/parity/issues/8774) I was able to pin-point the location to the way that IPC-Server and PubSubSession are interacting leading to an internal circle of never ending futures. Which in turn means we are keeping those connections around even after they've terminated, keep the socket open and - ultimatily - leak those connections as well as memory, causing [Parity to be oom-killed](https://github.com/paritytech/parity/issues/8618) (at least I suspect this error to be the cause of that error. Can't rule out there might be another leak).

[I've commited a short example triggering that behaviour, together with some code comments](https://github.com/gnunicorn/jsonrpc/commit/911ea0d450d36dfc61d8da70e61e9545a850e782) of the cause (IMHO) [in this branch](https://github.com/gnunicorn/jsonrpc/tree/leaking-ipc-connections-example).

To reproduce this bug, check out the [`leaking-ipc-connections-example` branch](https://github.com/gnunicorn/jsonrpc/tree/leaking-ipc-connections-example), cd into `ipc` and run

`RUST_LOG=ipc=trace cargo run --example with-pubsubsession`

Now have something connect to the open socket `/tmp/json-ipc-test.ipc` and immediately close again or die, like so:
```bash
#!/bin/sh -e
for i in `seq 0 1000`
do
    echo $i
    nc localhost 30303 </dev/null >/dev/null &
    pid=$!
    sleep 0.1
    kill $pid
done;
```

You'll see a bunch of messages appear in the example looking something like
```
    Finished dev [unoptimized + debuginfo] target(s) in 4.23 secs
     Running `/home/ben/dev/parity/jsonrpc/target/debug/examples/with-pubsubsession`
TRACE 2018-06-05T10:33:41Z: jsonrpc_ipc_server::server: Accepted incoming IPC connection: 1
TRACE 2018-06-05T10:33:41Z: with_pubsubsession: ext
TRACE 2018-06-05T10:33:41Z: jsonrpc_ipc_server::server: Accepted incoming IPC connection: 2
TRACE 2018-06-05T10:33:41Z: with_pubsubsession: ext
TRACE 2018-06-05T10:33:41Z: jsonrpc_ipc_server::server: Accepted incoming IPC connection: 3
TRACE 2018-06-05T10:33:41Z: with_pubsubsession: ext
```

Notice how the [closing message `Peer: service finished`](https://github.com/paritytech/jsonrpc/blob/7adb1ae60ffb5872976a924d0f95e93b60ef775e/ipc/src/server.rs#L181) is absent -- connections aren't dropped even though the peer is gone.

You can also watch it grow the open file handlers with lsof (e.g. ```while true; do echo "`date +%s` : `lsof -c with-pubs | wc -l`"; sleep 5; done```)

**Comment by dvdplm** [comment]
For posterity, here's a repeat-script that worked for me (thanks @debris):

```
#!/bin/sh -e
for i in `seq 0 1000`
do
    echo $i
    nc -U /tmp/json-ipc-test.ipc </dev/null >/dev/null &
    pid=$!
    sleep 0.1
    kill $pid
done;
```

(also, om macos, `brew uninstall netcat` if you have it)
