### ISSUE TITLE
server design flaw

### ISSUE THREAD

**Issue by debris** [paritytech/jsonrpc#278]
jsonrpc servers use `remote().spawn(|handle|  { .. })` to handle incoming connections. 

https://github.com/paritytech/jsonrpc/blob/3e358b48b71bf90dc60b4099de47e65b030dc319/ipc/src/server.rs#L116

According to [tokio-core documentation](https://tokio-rs.github.io/tokio-core/tokio_core/reactor/struct.Remote.html#panics)

> This method will **not** catch panics from polling the future f. If the future panics then it's the responsibility of the caller to catch that panic and handle it as appropriate. 

This is a serious design flaw, cause panics are silently ignored

**Comment by tomusdrw** [comment]
I'm not entirely sure how are we supposed to fix it, afaict there is no way of spawning a future on the event loop that actually catches panics (why would it anyway?).
Panicking future should just kill event loop and I think that's exactly what's happening and imho it's fine.

**Comment by rphmeier** [comment]
> This method will not catch panics from polling the future f. If the future panics then it's the responsibility of the caller to catch that panic and handle it as appropriate.

probably some confusion about what "catching panics" means. the default behavior is probably what @tomusdrw meant.

**Comment by tomusdrw** [comment]
Closing, since I don't see what we can do here.

**Comment by rphmeier** [comment]
There is actually `future.catch_panic`
