### ISSUE TITLE
Macros with &mut self methods

### ISSUE THREAD

**Issue by omimo** [paritytech/jsonrpc#287]
Hello!

I'm trying to use the macros to create a method that needs to use a mutable reference to self as follows:

```rust
build_rpc_trait! {
    pub trait NCRpc {
        #[rpc(name = "mut_method")]
        fn mut_method(&mut self, u64) -> Result<String>;
    }
}
```

which gives me the following error: 

```
error: no rules expected the token `(`
  --> proj/src/lib.rs:59:1
   |
59 | / build_rpc_trait! {
60 | |     pub trait NCRpc {       
61 | |         #[rpc(name = "mut_method")]
...  |
74 | |     }
75 | | }
   | |_^
   |

```

I was wondering if this is a bug or it is not possible to do this using macros.

Thanks for your help.

**Comment by tomusdrw** [comment]
Unfortunatelly it's not possible, the RPC method handlers are required to be `Send + Sync`, because the transport might be multi-threaded.

You need to wrap any mutability into `Mutex`es or `RwLock`s.

**Comment by omimo** [comment]
Makes sense. Thanks for the clarification.
