### ISSUE TITLE
Update hyper to 0.12

### ISSUE THREAD

**Issue by c0gent** [paritytech/jsonrpc#298]
I see that [this PR](https://github.com/paritytech/jsonrpc/pull/274) has been sitting for a while. I'd like to make the changes necessary to update hyper. I want to remove the rest of `tokio-core` from Parity due to its deprecation (migrate to `tokio`) and I'll need to update the reactor `Handle` to do that.

Is there anything in particular I should to be concerned about? Has anyone else looked into this?

**Comment by tomusdrw** [comment]
Thanks for jumping on it, I started the migration some time ago (just pushed `td-hyper` branch), there is some work involved in changing the way we handle headers (hyper removed the typed headers), but everything should be doable.

**Comment by c0gent** [comment]
Is there any particular reason to keep the [`RpcEventLoop`](https://github.com/paritytech/jsonrpc/blob/master/server-utils/src/reactor.rs#L100) single threaded (i.e. using a single Tokio Reactor all by itself) in the `Spawned` configuration? It's usually sub-optimal except maybe in micro-benchmarks and other special cases. I'll be removing the `CpuPool` from `Parity` anyway and its reactor will be paired with a thread pool automatically so when `RpcEventLoop` is in the `Shared` configuration it will be running on a thread pool (unless jsonrpc needs special treatment).

This may be something you guys have tested already and maybe there is some particular reason you want to stay single threaded. If that's the case I can make sure that all `jsonrpc` tasks stay that way without any trouble (though I'd probably urge you to reconsider). Otherwise I'll proceed with converting it to the standard tokio configuration (using a [`Runtime`](https://docs.rs/tokio/0.1.7/tokio/runtime/struct.Runtime.html)).

**Comment by tomusdrw** [comment]
We wanted to have a handle that closes the server when dropped. And to simplify spawning a new server if you don't really care that much for async/tokio stuff.

It's fine to convert it to `Runtime`, I can review the changes even if unfinished if you are unsure about the approach.

**Comment by c0gent** [comment]
So far the only API change I was planning to make is simply renaming `server_utils::reactor::Remote` to `Executor`. I'm not sure about that though. It's ability to close the server, etc. remains unchanged. I might rename the reactor module. No functionality anywhere will be removed or significantly changed.

You can see the changes on [this branch](https://github.com/c0gent/jsonrpc/tree/c0gent-hyper). So far, I've mostly finished changes to the [`server-utils`](https://github.com/c0gent/jsonrpc/tree/c0gent-hyper/server-utils) and [`tcp`](https://github.com/c0gent/jsonrpc/tree/c0gent-hyper/tcp) crates. `tcp` provides the best example of what will change (virtually nothing from the outside). I got slowed down working on the the `ipc` due to the changes I had to make to [`tokio-named-pipes`](https://github.com/poanetwork/tokio-named-pipes) and [`parity-tokio-ipc`](https://github.com/poanetwork/parity-tokio-ipc) but the changes to `ipc` and `http`, etc. will be mostly along the same lines as those in `tcp`. A fairly straightforward migration.

**Comment by c0gent** [comment]
Just an update: I haven't had time to work on this since last week and I have some travel coming up soon but I'm pretty much down to the final pieces and I'll do my best to get a PR submitted within in the next few days.

**Comment by jackcmay** [comment]
Is this still in motion?

**Comment by c0gent** [comment]
PR is here: https://github.com/paritytech/jsonrpc/pull/303

Integrating similar changes into Parity (to properly test the changes made by #303) is largely blocked by: https://github.com/paritytech/parity-ethereum/issues/9533

A WIP branch for those changes is: https://github.com/poanetwork/parity-ethereum/tree/c0gent-tokio
