### ISSUE TITLE
IPC server currently broken on Windows.

### ISSUE THREAD

**Issue by pinkisemils** [paritytech/jsonrpc#309]
Due to recent updates to `parity-tokio-ipc`, the IPC server is broken on Windows. Updating the dependency to the `master` branch instead of the `stable` fixes the `parity-tokio-ipc` build, but then it is no longer compatible with the event loop abstraction implemented in the `server_utils` crate. Pinning the commit ID for a _good_ version of `parity-tokio-ipc` doesn't help because the breakage is introduced by `tokio-named-pipes`. The issue is that the current master of `parity-tokio-ipc` is compatible with newer versions of tokio, does that mean that in the short term the collection of `jsonrpc` crates will migrate to the newer versions of tokio?

**Comment by tomusdrw** [comment]
We plan to migrate to new tokio eventually, but I don't expect it to happen soon. I think we will wait for `futures` 0.2 to stabilise first.

**Comment by tomusdrw** [comment]
Current master is buildable, but you need to manually pin `parity-tokio-ipc` to a previous revision with `cargo update -p parity-tokio-ipc --precise <revision>` (most likey `<revision> = b4a6cdf7d9b1e51c5d744d7f47d391a69a943232`)

**Comment by pinkisemils** [comment]
The build still fails on Windows because `parity-tokio-ipc`'s dependencies are not pinned (namely `tokio-named-pipes`), and require newer versions of tokio.

**Comment by pinkisemils** [comment]
I'll gladly put in the effort to fix whatever needs fixing, but as of now, it's really hard to know what I should be working towards.

**Comment by NikVolf** [comment]
I'll make a branch with pinned version

**Comment by tomusdrw** [comment]
Fixed, we now use crates.io versions.
