### ISSUE TITLE
build fails because of upstream change?

### ISSUE THREAD

**Issue by zippy** [paritytech/jsonrpc#341]
Hi folks, as of this morning it looks like your build is failing because of an upstream change here:

https://github.com/tomusdrw/ws-rs/blob/4baef2dc1abc8e216559af51cfc120bbcc777e21/src/handshake.rs#L435

I'm seeing this when doing a `cargo test` on a vanilla checkout of `master`:

```
   Compiling jsonrpc-ws-server v9.0.0 (/home/eric/code/metacurrency/holochain/jsonrpc/ws)
   Compiling jsonrpc-tcp-server v9.0.0 (/home/eric/code/metacurrency/holochain/jsonrpc/tcp)
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> ws/src/session.rs:367:22
    |
367 |     let mut forbidden = ws::Response::new(403, "Forbidden");
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters

error[E0599]: no method named `set_body` found for type `ws::Response` in the current scope
   --> ws/src/session.rs:368:12
    |
368 |     forbidden.set_body(
    |               ^^^^^^^^

```

**Comment by tomusdrw** [comment]
@zippy use `Cargo.lock` to keep the versions locked for your project
`cargo update -p ws --precise f12d19c4c19422fc79af28a3181f598bc07ecd1e`

**Comment by tomusdrw** [comment]
Closing, cause it should be resolved.
