### ISSUE TITLE
Unsubscribe from notifications with jsonrpc_pubsub

### ISSUE THREAD

**Issue by izolyomi** [paritytech/jsonrpc#342]
I've found the nicely designed and generic crates jsonrpc_core and jsonrpc_pubsub and working on integrating them into my project. So far I'm mostly happy about their usability, but trying to implement unsubscribing from notifications using `PubSubHandler::add_subscription()` I seem to have hit a wall.

I assumed that the whole point of `PubSubMetadata` is to keep your session state within it, including subscriptions to be able to unsubscribe. However, `UnsubscribeRpcMethod` receives only a `SubscriptionId` but no metadata (i.e. session) at all. Checking some utility macros of the separate jsonrpc_macro crate (that I wouldn't like to use) I see that a very complex independent structure is built and converted all around to use `MetaIoHandler::extend_with()` in a completely different way than `PubSubHandler::add_subscription()`.

As all of Parity's own examples simply ignore implementing an unsubscribe (see e.g. [this example](https://github.com/paritytech/jsonrpc/blob/master/pubsub/examples/pubsub.rs#L55)), I have the following questions/requests:

1. Is it intentional design that the session is hidden within unsubscribe lambdas? Could you please give some documentation or rationale about this?
2. a, In case of an intentional design, could you please give a minimal working example that actually implements unsubscribing from notifications?
2. b, If unintentional, could you please add a metadata parameter to `UnsubscribeRpcMethod` just as in any other method?

**Comment by tomusdrw** [comment]
@izolyomi interesting insight, thank you very much for it.

1. The fact that unsubscribe doesn't receive metadata seem to be an oversight, I quickly skimmed through the code and couldn't find any reason for it.
2. They way we use subscriptions in Parity ethereum usually modifies some external state (not `Metadata`), and unsubscribing is just removing an entry from an external `HashMap` and dropping the `Sink`.

I'll have a look today and will try to introduce metadata to `unsubscribe` as well.

**Comment by izolyomi** [comment]
@tomusdrw wow, thank you for the lightning fast reply.

2. You might better see where I'm coming from if I explain my approach a bit more. I currently have a notification stream which I forward (simply with `Stream::forward`) to the sink of the session. During unsubscribing, I have to cancel this task somehow, so I planned to add a `oneshot::channel` and use a `forward_fut.select(oneshot_rx)` to be able to cancel sending more notifications. I planned to use the session to access the `Sender` for the channel, but it's currently inaccessible from `unsubscribe`.
I might have used an unfortunate architecture, but I couldn't find any realistic examples in your codebases.

I'm happy if this can be solved in any way, e.g. by adding the metadata to unsubscribe. Thank you very much in advance.

**Comment by tomusdrw** [comment]
@izolyomi yeah, `oneshot` channel and `select` seems like a good solution. I'm not sure why you need the `Sender` for that though - it seems that you need some external context (to get the notification stream) anyway, so oneshot channel could also be moved to unsbuscribe method?
Anyway, I've just made #344, please have a look if this answers all your questions.

**Comment by izolyomi** [comment]
@tomusdrw It wasn't as simple because I have to access the `oneshot::Sender` from `unsubscribe`. Since I just created it within `subscribe()`, I need some way to pass it around, e.g. within the session. A trimmed down version of what I mean is:

```handler.add_subscription( "event",
    ( "subscribe", move |params, mut meta, subscriber| {
        let (cancel_tx, cancel_rx) = oneshot::channel();
        // Save cancel_tx somewhere to be accessible outside this lambda
        ...
        handle.spawn( fwd_events_fut.select(cancel_rx) );
    } ),
    ( "unsubscribe_events", |_id: SubscriptionId| {
        // Should access cancel_tx here
    } );```

Maybe there are better ways to solve this without a session, I'm not sure.

I've checked #344 and I can confirm it's exactly what I meant and I think it'll solve everything I'd need, I hope it's also useful for others. Thank you again for the amazing reaction time and work.

**Comment by tomusdrw** [comment]
@izolyomi yeah, you would need an `Arc<Mutex<_>>` in the context and pass clones of it to both functions - that way the `subscribe` method can populate something within this struct and `unsubscribe` can use it.
See the example I've added in the PR, where `Arc<AtomicBool>` is used to stop the subscription (i.e. stop the thread and drop the sink)
