### ISSUE TITLE
Example request

### ISSUE THREAD

**Issue by MathieuDutSik** [paritytech/jsonrpc#377]
The JSONRPC has a number of useful examples.

However, none of the example that are given in the code show how to implement a "close()" operation.
I tried the following for the `minihttp` server:
```
    io.add_method("terminate", |_: Params| {
        println!("Processing a terminate command");
        server.close();
	Ok(Value::String("Successful termination of the server".into()))
    });
```
However, this does not compile since the add_method has to be before the creation of
the `server` variable and so `server` is undefined at this point.

Any help on this matter would be helpful. While I learn a lot from the examples, some
topics are not considered in them and additional documentation is much welcomed.

**Comment by tomusdrw** [comment]
Indeed the server is not available when `IoHandler` is being created. The `core` part is completely transport-agnostic and could actually be running on multiple transports.
What you can do however is:
```rust
let server_handle = Arc<Mutex<Option<ServerHandle>>>;
let for_io = server_handle.clone();
io.add_method("terminate", move |_| {
  if let Some(sh) = for_io.lock().take() {
    sh.close();
  }
});
// start serve
let server = ...;
*server_handle.lock() = Some(server);
```

hope that helps.
