### ISSUE TITLE
Request object params can only be an array for delegate methods

### ISSUE THREAD

**Issue by andreykaipov** [paritytech/jsonrpc#387]
Take the following example which spins up an HTTP server accepting two methods - `add_delegate` and `add_nondelegate`.

```rust
use jsonrpc_core::{IoHandler, Compatibility, Value, Params, Result};
use jsonrpc_derive::rpc;
use jsonrpc_http_server::ServerBuilder;
use serde::Deserialize;

#[derive(Deserialize, Debug)]
pub struct AddArgs {
    a: u8,
    b: u8,
}

#[rpc]
pub trait Rpc {
    #[rpc(name = "add_delegate")]
    fn add(&self, _: AddArgs) -> Result<u8>;
}

struct RpcImpl;
impl Rpc for RpcImpl {
    fn add(&self, args: AddArgs) -> Result<u8> {
        Ok(args.a + args.b)
    }
}

fn add(params: Params) -> Result<Value> {
    let args: AddArgs = params.parse().unwrap();
    let sum = args.a + args.b;
    Ok(Value::Number(sum.into()))
}

fn main() {
    let mut io = IoHandler::with_compatibility(Compatibility::V2);
    io.extend_with(RpcImpl.to_delegate());
    io.add_method("add_nondelegate", add);

    ServerBuilder::new(io)
        .start_http(&"127.0.0.1:3030".parse().unwrap())
        .unwrap()
        .wait();
}
```

To be able to call the `add_delegate` method successfully, we must wrap our params in an array. Otherwise, we'll get the following error:
```bash
$ curl -H 'Content-Type: application/json' -XPOST http://localhost:3030 -d '{"jsonrpc":"2.0", "method":"add_delegate", "params":{"a":2, "b":3}, "id":1}'
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: invalid type: map, expected a tuple of size 1."},"id":1}
```

The `add_nondelegate` method doesn't have this issue because we're able to control the expected type of the params by parsing them into an appropriate struct. I tried looking through the library to see if there's a way to force delegate methods to not wrap their params around an array, but unfortunately I couldn't find anything.

While the JSON-RPC 1.0 spec requires params to be an array, the 2.0 spec doesn't. Is there a way to do this with delegate methods?

**Comment by tomusdrw** [comment]
@andreykaipov the `jsonrpc-derive` crate is a bit more opinionated than the `core` stuff. I'm happy to make it more flexible (if possible), but don't really have one good idea how to do it.

The options I see:
1. Optional attribute for the entire trait to allow sending the parameter without `[]` when there is only one parameter to the method. (i.e. accept both `params: [{}]` and `params: {}` if the flag is on)
2. Require choosing either of those behaviours
3. Either option (1) or (2) but on the method level.

I don't see a way to handle two (or more) argument methods in any sensible way so I think it should be denied.
Which of the options do you prefer? Also CC @ascjones what's your thoughts on this?

**Comment by ascjones** [comment]
According to the [spec](https://www.jsonrpc.org/specification):

> If present, parameters for the rpc call MUST be provided as a Structured value. Either by-position through an Array or by-name through an Object.
> - by-position: params MUST be an Array, containing the values in the Server expected order.
> - by-name: params MUST be an Object, with member names that match the Server expected parameter names. The absence of expected names MAY result in an error being generated. The names MUST match exactly, including case, to the method's expected parameters.

I interpret this to mean that if we were using a `by-name` parameter structure then
```
"params":{"a":2, "b":3}
```
would actually map to:
```
fn add(&self, a: u64, b: u64) -> Result<u8>;
```
So to be true to the spec, if using `by-name` mode then the request would actually look like this:
```
"params":{args: {"a":2, "b":3}}
```
I think then that we could add a flag at the trait level to choose which mode to use for all methods, but you would have to use the above request format for a single parameter object i.e. the params object on its own would still not work. 

So depends really how strict we want to be about adhering to the spec. I think better to be strict - keeps things simple. And anyway as you demonstrate using raw `jsonrpc-core` allows the flexibility to bend the rules here.

**Comment by ascjones** [comment]
Reading again we should probably support both parameter formats to be spec compliant (emphasis mine):

> Either by-position through an Array **or** by-name through an Object

So calling `fn add(&self, a: u64, b: u64)` would work with both
```
"params":{"a":2, "b":3}
"params":[2, 3]
```

**Comment by andreykaipov** [comment]
@ascjones I interpret the _"or"_ from your excerpt to be exclusive, so specifying the mode in the `rpc` attribute (whether at the trait or method level) should be an option. It can default to `by-position` to maintain compatibility and not introduce a breaking change.

---

For a single-argument function, I think there's a natural interpretation for `by-name` params. The following:
```
#[rpc(name = "double", params = "by-name")]
fn double(&self, a: u8) -> Result<u8>;
```
should accept something like
```
"params": {"a": 2}
```

Or in the case of a struct that can be deserialized:
```
#[rpc(name = "add", params = "by-name")]
fn add(&self, params: AddArgs) -> Result<u8>;
```
should accept something like
```
"params": {"a": 2, "b": 3}
```

---

For a multi-argument function, how do we interpret `by-name` params? For the following:
```
#[rpc(name = "add", params = "by-name")]
fn add(&self, a: u8, b: u8) -> Result<u8>;
```
one approach is to also accept
```
{"a":2, "b":3}
```
However, I'd consider this approach to be inferior to just wrapping our arguments in a struct and using a single-argument method with a `by-name` params interpretation, especially for very large params. So, maybe we should only allow the `by-name` mode on single-argument methods? I think that's what you meant by _"it should be denied"_, right? @tomusdrw

---

Further, the `by-name` interpretation can preferably be coerced into a `by-position` interpretation by specifying `Vec<_>` or another similar array type. This allows for easily specifying arbitrarily large arrays as our params.

**Comment by tomusdrw** [comment]
> So, maybe we should only allow the `by-name` mode on single-argument methods? I think that's what you meant by _"it should be denied"_, right?

Yes, it still has some corner cases though, for instance, if we go with this:
```
#[rpc(name = "add", params = "by-name")]
fn add(&self, params: AddArgs) -> Result<u8>;

"params": {"a": 2, "b": 3}
```
then this, should be forbidden, cause it's not allowed by the spec:
```
#[rpc(name = "double", params = "by-name")]
fn double(&self, a: u8) -> Result<u8>;

"params": 2
```

So we can only allow types that serialize to objects or arrays which is hard (or impossible) to detect. Perhaps we should allow defining such method but it won't be possible to call it, but it seems misleading as well.

Now I think about it maybe instead of providing this feature on macro-level we will rather allow to receive raw params object?

```
#[rpc(name = "double", rawParams)]
fn double(&self, params: Params) -> Result<u8> {
   let addArgs: AddArgs = params.parse()?;
}
```

This makes it the most flexible and prevents ambiguity or confusion. It always have to be single-parameter method (variable name does not matter) and then you can parse it either as array, object or both if you need it.

**Comment by ascjones** [comment]
@tomusdrw That's a good idea. Minimum complexity, maximum flexibility. We can implement that regardless of whether/how we support `by-name` param structure, so will create a new issue.

**Comment by andreykaipov** [comment]
> Now I think about it maybe instead of providing this feature on macro-level we will rather allow to receive raw params object? [...] It always have to be single-parameter method (variable name does not matter) and then you can parse it either as array, object or both if you need it.

If I understand correctly, by receiving the raw params object, we're essentially allowing `jsonrpc-derive` to behave like `jsonrpc-core`, right?

**Comment by tomusdrw** [comment]
Yes, basically you'd be able to use `derive` for array params, and then fallback to core-like behaviour if that's not sufficient.
That said, if we figure out how to do by-name params properly we can implement that too.

**Comment by andreykaipov** [comment]
If that's the case, I'm happy closing this issue in favor of the one @ascjones created above! If it works out, I don't think distinguishing between by-name or by-position params will be necessary. Thank you both for the discussion! 😄
