### ISSUE TITLE
Introduce clippy into CI pipeline 

### ISSUE THREAD

**Issue by ascjones** [paritytech/jsonrpc#396]
Suggested by @kirushik in #395. We would need to use a `.clippy.toml` file to whitelist the lints we care about.

**Comment by kirushik** [comment]
It should be really straighforward to add: https://github.com/rust-lang/rust-clippy#travis-ci

**Comment by ascjones** [comment]
@kirushik be my guest :smile:

**Comment by dvc94ch** [comment]
Closing as duplicate of #418
