### ISSUE TITLE
IoHandle dependent object (of type Arc<>) is not released after HTTP server closed or dropped

### ISSUE THREAD

**Issue by boqiu** [paritytech/jsonrpc#402]
Everything goes well before upgrading the jsonrpc from branch [parity-1.11](https://github.com/paritytech/jsonrpc/tree/parity-1.11) to v10.1.0 (on crates.io). It seems that the RPC HTTP server in new version cannot correctly release the referenced object.

In details, when an IoHandler reference any object of type Arc<> and the RPC is called, the RPC HTTP server will not reduce the reference account of Arc when closed or dropped. But if RPC HTTP server started and not called, then the ref count will be reduced as expected when server closed or dropped. See sample codes as following, and is there any way to mitigate such problem?

```rust
use jsonrpc_derive::rpc;
use jsonrpc_core::Result;
use jsonrpc_core::IoHandler;
use jsonrpc_http_server::ServerBuilder;
use std::sync::Arc;

#[rpc]
pub trait Rpc {
    #[rpc(name = "add")]
    fn add(&self, a: u64, b: u64) -> Result<u64>;
}

pub struct RpcImpl {
    foo: Arc<Foo>,
}

impl Drop for RpcImpl {
    fn drop(&mut self) {
        println!("=================== drop rpc impl ======================");
    }
}

impl Rpc for RpcImpl {
	fn add(&self, a: u64, b: u64) -> Result<u64> {
		Ok(self.foo.mul(a, b))
	}
}

struct Foo {}
impl Foo {
    fn mul(&self, a: u64, b: u64) -> u64 { a * b }
}

fn main() {
    let foo = Arc::new(Foo{});
    println!("foo strong count: {}", Arc::strong_count(&foo)); // foo ref count should be 1

    let mut io = IoHandler::new();
    io.extend_with(RpcImpl{foo: foo.clone()}.to_delegate());   // foo ref count changed to 2
    let server = ServerBuilder::new(io)
        .start_http(&"127.0.0.1:3030".parse().unwrap())
        .unwrap();

    println!("JSON RPC HTTP server started ...");
    println!("foo strong count: {}", Arc::strong_count(&foo)); // foo ref count should be 2

    // sleep 5 seconds to allow to call add RPC.
    std::thread::sleep(std::time::Duration::from_secs(5));

    // close or drop the http server.
    // Ideally, the RpcImpl should be dropped immediately or in a short time.
    // So, the foo ref count should change to back to 1
    server.close();
    // std::mem::drop(server);

    println!("JSON RPC HTTP server closed/dropped.");

    // If the add RPC called, the foo ref count is 2.
    // Otherwise, the foo ref count is 1.
    // If the program depend on the ref count to clean up something,
    // the cleanup will never happen.

    for _ in 0..10 {
        let ref_count = Arc::strong_count(&foo);
        println!("foo strong count: {}", ref_count);

        if ref_count == 1 {
            break;
        }

        std::thread::sleep(std::time::Duration::from_secs(1));
    }
}
```

**Comment by tomusdrw** [comment]
I couldn't reproduce the issue, for me the program stops every time and the drop impl is being run. Tried both debug and release modes.
You can find the full sample here and the log from running the code with traces:
[logs.txt](https://github.com/paritytech/jsonrpc/files/2952078/logs.txt)
[code.zip](https://github.com/paritytech/jsonrpc/files/2952082/reproduce.zip)

What's your `rustc --version`? Would you mind re-running the example with `RUST_LOG=trace` and upload the logs here?

**Comment by boqiu** [comment]
By default, the drop impl of RpcImpl will be executed, as I mentioned in the code comments that everything goes well if no RPC called.

The problem ONLY OCCUR when RPC HTTP server started, and make a RPC call (via postman or curl). Note, the program only sleep 5 seconds to allow external RPC call:
``` rust
    // sleep 5 seconds to allow to call add RPC.
    std::thread::sleep(std::time::Duration::from_secs(5));
```

BTW, my rustc version is 1.32.0, and use rust 2018 edition. Here is the Cargo.toml:
```
[package]
name = "hello_world"
version = "0.1.0"
authors = ["boqiu <82121246@qq.com>"]
edition = "2018"

[dependencies]
# hello_utils = { path = "hello_utils" }
# ethereum-types = "0.4"
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc", tag = "v10.0.0" }
jsonrpc-macros = { git = "https://github.com/paritytech/jsonrpc", tag = "v10.0.0" }
jsonrpc-derive = { git = "https://github.com/paritytech/jsonrpc", tag = "v10.0.0" }
jsonrpc-pubsub = { git = "https://github.com/paritytech/jsonrpc", tag = "v10.0.0" }
# jsonrpc-tcp-server = "10.1.0"
jsonrpc-http-server = { git = "https://github.com/paritytech/jsonrpc", tag = "v10.0.0" }

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

parking_lot = "0.6"
```

**Comment by boqiu** [comment]
I just tried your zipped code, and reproduced it easily.

In addition, I tested it on Windows 10 x64. However, Ubuntu 18 should be the same, since our CI pipeline failed due to such problem.

**Comment by tomusdrw** [comment]
@boqiu I do make a call, you can find that it's processed in the logs. Tried both with and without the call as well (sorry forgot to mention in my previous comment).

**Comment by boqiu** [comment]
See my reproduce trace below:

[rep_trace.txt](https://github.com/paritytech/jsonrpc/files/2952226/rep_trace.txt)

**Comment by boqiu** [comment]
@tomusdrw Just found that it works fine when call the RPC via curl:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"add","params":[3,6],"id":1}' -H "content-type: application/json" 127.0.0.1:3030
```

But, when I call the RPC via postman, the problem occur.

**Comment by tomusdrw** [comment]
Might be an issue with keep alive then, would you mind trying setting `keep_alive` to false on the server side?
```
ServerBuilder::new(io).keep_alive(false).start...
```

**Comment by boqiu** [comment]
Yes, exactly. I followed your way that to set `keep_alive` to false, the problem mitigated.

What is keep_alive used for? Any impact to my program if set it to false?

**Comment by boqiu** [comment]
In fact, my program never set the keep-alive explicitly, and it is `true` by default in both branch parity-1.11 and v10.1.0. So, it that a regression?

**Comment by tomusdrw** [comment]
It allows the TCP connection between client and server to be kept open after the HTTP payload is send. When it's open the next http request can be sent over the same connection which should result in lower latency (cause the tcp handshake is not needed). It's controlled by the client, but is also assumed on by default in HTTP1.1.

I don't understand yet why it prevents the server to be closed correctly (I suspect some retain cycle either in our code or in hyper).

Re: versions, I have to look closer what has been changed, but this https://github.com/paritytech/jsonrpc/pull/333 might be responsible for the change in the behaviour.

**Comment by boqiu** [comment]
I can mitigate such problem by some other ways in our program temporarily. Anyway, I'm looking forward to the root reason and hotfix. Thanks a lot!
