### ISSUE TITLE
Send a notification from the server

### ISSUE THREAD

**Issue by euclio** [paritytech/jsonrpc#403]
Is it possible to send a notification from the server side? I'm trying to write a language server using this crate, and I need to be able to send a new notification to the client after receiving a notification from the client:

```rust
let mut io = jsonrpc_core::IoHandler::new();

{
    io.add_notification("textDocument/didOpen", move |params: Params| {
        let params: DidOpenTextDocumentParams = params.parse().unwrap();
           
        // compute diagnostics...

        // FIXME: notify the client via `publishDiagnostics` here
    });
}
```

**Comment by tomusdrw** [comment]
@euclio This library only implements the server side and core types for JSON-RPC that can be used to build a client.
You can find a client build with `jsonrpc-core` here: https://github.com/mullvad/jsonrpc-client-rs.

That said, we also support a custom extension to JSON-RPC protocol allowing to implement Pub/Sub pattern. The flow is as follows:
1. The client calls a regular RPC method to subscribe and gets subscription id in the response.
2. The server now has a way to send RPC notifications to the client with that particular subscription id
3. The client can unsubscribe at any moment by calling a special RPC method, or it is unsubscribed automatically when disconnected.

Note that subscriptions are only available on connection-persistent, duplex channels (WS, IPC, TCP and not HTTP).
You can find subscription  example here: 
https://github.com/paritytech/jsonrpc/blob/master/derive/examples/pubsub-macros.rs
