### ISSUE TITLE
Actix Integration

### ISSUE THREAD

**Issue by 0xpr03** [paritytech/jsonrpc#415]
Hi,
while trying to integrate this with actix I stumbled upon runtime issues due to actix using another tokio runtime model, making actix-calls panic.
To not re-implement everything as Arbiter I created a small jsonrpc-core -> actix-web bridge.
So if anyone is also having this problem, this is my bridge for running jsonrpc on top of actix-web:
https://gist.github.com/0xpr03/b099c420170735a8c3ee03db5657fe1e

**Comment by micfan** [comment]
Actix Integration +1

**Comment by dvdplm** [comment]
Nice! Let us know if you decide to write a blog post or expand on this otherwise and we'd be happy to review/retweet etc. :)

**Comment by 0xpr03** [comment]
I'm not sure what you mean with that ?
If anyone wants to use jsonrpc on top of actix they can use my snippet.
It probably has to be updated a little bit for actix-web 1.0 but I'm not sure.

**Comment by 0xpr03** [comment]
Updated gist for actix-web 1.0

**Comment by tomusdrw** [comment]
Closing, since the issue with link to a gist will be searchable anyway and I don't see any immediate actions we can take in the library. We could include the gist as an example in the repo, but I wonder where we draw the line - which libraries are worth having examples?
