### ISSUE TITLE
Does the HTTP Server Spawn Threads?

### ISSUE THREAD

**Issue by fredfortier** [paritytech/jsonrpc#423]
I'm running the HTTP Server in a manner basically identical to the `http_async.rs` example. When two calls are received at the exact same, it seems like the server spawns a new thread. Is this true or are the requests always queued in the Tokio event loop?

**Comment by tomusdrw** [comment]
No, the `ServerBuilder` only starts one thread for the Tokio-core event loop (unless configured different via `.threads(n)`) all incoming requests are queued and executed on that one thread.
Please re-open in case you have further questions or believe the server does not work as expected.
