### ISSUE TITLE
username/password Authentication

### ISSUE THREAD

**Issue by nkostoulas** [paritytech/jsonrpc#430]
Is there any way to do username password authentication?

**Comment by tomusdrw** [comment]
@nkostoulas the json-rpc protocol itself is stateless, so you would have to implement it on your own, example workflow:
1. User calls `login` RPC method with user/pass and gets a token
2. The token has to be included as parameter to other RPC calls.

Another option is to implement something on transport level, for instance you can check HTTP basic auth in HTTP server middleware (see example here: https://github.com/paritytech/jsonrpc/blob/master/http/examples/http_middleware.rs#L14)

Yet another option if you are only using stateful transport (like WS or TCP) is to realise the first workflow but without a need to pass the token every time:
1. User calls `login` RPC and gets `true/false`
2. The `login` RPC method saves user details inside `Metadata` object
3. Now either methods can check the user details by accessing metadata or you can do it for all methods inside `jsonrpc-core` middleware.

I'm closing this one cause I think the question is too generic, please specify your exact use case and either reopen or create a separate issue.
