### ISSUE TITLE
Custom Error Codes

### ISSUE THREAD

**Issue by fredfortier** [paritytech/jsonrpc#434]
I need to catch application errors and implement custom error codes to the returned JSON-RPC errors. The [JSON-RPC Specs](https://www.jsonrpc.org/specification) suggests that codes -32000 to -32099 should be used for "implementation-defined server-errors". I couldn't find any easy way to do this in the documentation. Is this a supported feature? If so, any pointer (to the doc or sources) would be appreciated.

**Comment by ascjones** [comment]
Just return `Err(Error::new(ErrorCode::ServerError(your_err_code)))` from the rpc method.

**Comment by tomusdrw** [comment]
And from the code point of view, if you are using `jsonrpc-derive` it's best to define your own custom error type and implement `From<YourError> for jsonrpc_core::Error`:
```rust
pub enum MyError {
  MyFailure,
  SecondFailure,
}

impl From<MyError> for jsonrpc_core::Error {
  fn from(e: MyError) -> Self {
    match e {
      MyError::MyFailure => Error::new(ErrorCode::ServerError(-34)),
      MyError::SecondFailure => Error::new(ErrorCode::ServerError(-35)),
    }
  }
}
```

and just use `MyError` in trait definition.

**Comment by fredfortier** [comment]
@tomusdrw This is what I was looking for, thanks! I'll let you guys close the issue since you tagged it as documentation.
