### ISSUE TITLE
stdio server blocks on each method call

### ISSUE THREAD

**Issue by pietgeursen** [paritytech/jsonrpc#445]
Is this expected behavior? Some of my method calls can be very long (10s of seconds) and this is a bit of a show stopper.

The current code does this:

```rust
	/// Will block until EOF is read or until an error occurs.
	/// The server reads from STDIN line-by-line, one request is taken
	/// per line and each response is written to STDOUT on a new line.
	pub fn build(&self) {
		let stdin = tokio_stdin_stdout::stdin(0);
		let stdout = tokio_stdin_stdout::stdout(0).make_sendable();

		let framed_stdin = FramedRead::new(stdin, LinesCodec::new());
		let framed_stdout = FramedWrite::new(stdout, LinesCodec::new());

		let handler = self.handler.clone();
		let future = framed_stdin
			.and_then(move |line| process(&handler, line).map_err(|_| unreachable!()))
			.forward(framed_stdout)
			.map(|_| ())
			.map_err(|e| panic!("{:?}", e));

		tokio::run(future);
	}
```

I've found that this hacky code gets me what I want but I'm not sure it's good enough for a PR:

```rust
	/// Will block until EOF is read or until an error occurs.
	/// The server reads from STDIN line-by-line, one request is taken
	/// per line and each response is written to STDOUT on a new line.
	pub fn build(&self) {
		let stdin = tokio_stdin_stdout::stdin(0);

		let framed_stdin = FramedRead::new(stdin, LinesCodec::new());

		let handler = self.handler.clone();
		let future = framed_stdin
                    .map_err(|e| panic!("{:?}", e))
                    .for_each(move |line| {
			let f = process(&handler, line)
                            .map(|s| {
                                println!("{}", s);
                            });

			tokio::spawn(f)
                    });

                tokio::run(future);
	}
```

I've tried a bunch of things to use the framed_stdout but I don't know tokio well enough and it's probably faster for someone who knows it better than me.

**Comment by tomusdrw** [comment]
What are you method handlers doing? If the RPC methods implementations are blocking then indeed they will be executed sequentially, because stdio server is just single-threaded.

You should either:
1. Convert the RPC method handles to be asynchonous (i.e. return a `Future`)
2. Or introduce a thread pool to execute tasks in it.

The (2) can be done using `Middleware` mechanism, see an example here:
https://github.com/paritytech/jsonrpc/blob/44c501bc4182c7fef7d56d0efc780cd7fbb98419/core/examples/middlewares.rs#L17

The idea would be to introduce a thread pool in the middleware and dispatch calls to `next()` within that pool.

This kind of middleware is a nice addition to the `jsonrpc-core` library, so I'd be happy to help with and accept a PR.

**Comment by pietgeursen** [comment]
> What are you method handlers doing?

Doing database requests. Some of the requests can be really long running. 

---

I think there's another piece of context here that I didn't explain.
Assume I make these two requests at the same time:

```json
{"jsonrpc": "2.0", "method": "veryLongRunningQuery", "params": {}, "id": 1}
{"jsonrpc": "2.0", "method": "veryFastQuery", "params": {}, "id": 2}
```

What I _want_ is that the result of request 2 is returned first. But I _think_ because the current implementation uses `and_then` the output ordering is guaranteed to match the input ordering.

That's why I used `for_each` in my code.

I just tried returning a future from my method handler and I still don't get the ordering I want.

Would making a middleware solve this problem?

**Comment by tomusdrw** [comment]
If you have blocking database requests, you indeed need multiple threads to run concurrent queries.

By default the `stdio` transport is single threaded, what you did with `tokio::spawn(f)` you've just utilised the default tokio runtime and the fact that it's multi threaded so it was able to process more requests in parallel.

However we can also implement the aforementioned `Middleware` that uses a separate thread pool, roughly:
```rust
// I'm not sure about the choice of this library though, it seems it was deprecated,
// but we still use old `futures`, so there might not be any alternatives.
use futures_cpupool::{CpuPool, CpuFuture};

#[derive(Default)]
struct PoolMiddleware(CpuPool);
impl<Meta: core::Metadata> core::Middleware<Meta> for PoolMiddleware {
	type Future = CpuFuture<Option<Response>, ()>;
	type CallFuture = middleware::NoopCallFuture;

	fn on_request<F, X>(&self, request: Request, meta: Meta, next: F) -> Either<Self::Future, X>
	where
		F: FnOnce(Request, Meta) -> X + Send,
		X: Future<Item = Option<Response>, Error = ()> + Send + 'static,
	{
		self.0.spawn(next(request, meta))
                // or
                // self.0.spawn(futures::future::lazy(move || next(request,meta)))
	}
}
```

We could also add some convenience methods, like `MetaIoHandler::with_thread_pool(5)` to produce a handler with this kind of middleware.

**Comment by tomusdrw** [comment]
Assuming resolved.
