### ISSUE TITLE
#436 was a breaking change

### ISSUE THREAD

**Issue by dimbleby** [paritytech/jsonrpc#453]
I see there was [discussion](https://github.com/paritytech/jsonrpc/pull/446#discussion_r300447309) about this - but #436 really was a breaking change.

Code like [this](https://github.com/autozimu/LanguageClient-neovim/blob/5491a64a07b259568e26981e5ec0d78ba8cec756/src/rpcclient.rs#L83-L86) for instance, that expected either `Success` or `Failure` does not compile any more, because it does not handle the `Notification` case.

It's a bit tedious - but I think the Right Thing To Do is to yank the breaking change and republish with a major version bump.

**Comment by ebkalderon** [comment]
I agree with this. Adding new variants to a public `enum` is a breaking change to the public API according to semver and should warrant a major version bump.

**Comment by tomusdrw** [comment]
Indeed, I haven't spotted that one of the core types has been extended. We will release 13.0 shortly and consider yanking 12.1.
