### ISSUE TITLE
`Output::Notification` variant is incorrect

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/jsonrpc#458]
Related: #453 

The type structure in `jsonrpc-core` should represent the protocol as closely as possible, hence having a `Notification` in the `Output` (and in turn `Response`) is incorrect and should be reworked to avoid it, since a response with no `id` and `method/params` fields is not valid.

**Comment by dvc94ch** [comment]
The output (from the perspective of the server) is a response or a notification. I don't see why that's a bug...

**Comment by tomusdrw** [comment]
`jsonrpc-core` should be based solely on the jsonrpc spec, and pub-sub is a custom extension to this.

So according to the spec the `Response` can only contain either a success or a failure. You can't send a request to the server and get a `Notification` (which is basically a method call request) back.

**Comment by dvc94ch** [comment]
But when parsing a message it can be a Success/Failure or a Notification... It was the simplest way to get it to work... I think I also tried another approach that didn't work out very nicely...

**Comment by tomusdrw** [comment]
I think we should be able to do a custom enum just for the client to avoid modifying `jsonrpc_core::Output`
