### ISSUE TITLE
Batch requests from client

### ISSUE THREAD

**Issue by ascjones** [paritytech/jsonrpc#463]
Support batch requests in `core-client` transports, and potentially in the `derive` client if we can come up with a nice API.

**Comment by tomusdrw** [comment]
In `rust-web3` I've implemented batch as a transport wrapper (i.e. defers sending until you tell it too).

For `derive()` I think an API like this would be nice:
```
// regular call
let result = client.call_something();

// batch call
let batch = client.batch();
let result = batch.call_something();
spawn(batch.send());
```
