### ISSUE TITLE
Support for async notifications

### ISSUE THREAD

**Issue by Vincent-P** [paritytech/jsonrpc#467]
Hello,
I am trying to make a LSP server with your library.
I am wondering why notification handlers can't return futures like method handlers, and what would be the easiest way to implement async notifications in my project.

Thanks,

**Comment by tomusdrw** [comment]
Notifications don't return anything by definition. We could in theory allow them to return `Future<Item=()>`, but with `tokio` runtime you should also be able to just spawn your future directly using `tokio::spawn(future)` inside the notification.

**Comment by Vincent-P** [comment]
Okay, thanks for your reply, `tokio::spawn(future)` works indeed.
