### ISSUE TITLE
FutureResult in RPC derive

### ISSUE THREAD

**Issue by onsails** [paritytech/jsonrpc#492]
I need to run a synchronous i/o inside a jsonrpc method.
To do this I'm creating tokio `ThreadPool` and constructing future using `blocking`.
As I understand RPC trait functions are supposed to return either `Result` or `FutureResult`.
Looking at the code of `FutureResult` I see that it assumes that returned future is already completed. 
How can I spawn a new future from other tokio pool and what rpc method's function signature should look like if my future signature is `Futures::Lazy<(), Box<dyn std::error::Error>`?

I'm continuously stumbling upon errors like this:
```
88 |                 }).into()
   |                    ^^^^ the trait `std::convert::From<futures::Lazy<[closure@src/pipe_server/rpc.rs:61:22: 88:18 self:_, run_id:_, id:_, ts:_], futures::future::PollFn<[closure@src/pipe_server/rpc.rs:62:33: 87:26 self:_, run_id:_, id:_, ts:_]>>>` is not implemented for `futures::Finished<(), std::boxed::Box<dyn std::error::Error>>`
```

**Comment by prettynatty** [comment]
Resolved by using `#[rpc(server)]` macro and `BoxFuture` instead of FutureResult.
Is it right way to go? If yes, should docs be updated?

**Comment by tomusdrw** [comment]
Do we use `FutureResult` in any docs? It's pretty much an internal typedef for the type returned by the entire `IoHandler` not single method. `BoxFuture` is indeed the way to go.

**Comment by prettynatty** [comment]
Yes, it's mentioned in examples: https://docs.rs/jsonrpc-derive/13.2.0/jsonrpc_derive/ https://github.com/paritytech/jsonrpc/blob/master/derive/examples/generic-trait.rs

**Comment by tomusdrw** [comment]
Oh, I thought you are talking about our internal `FutureResult`. The one linked here is just coming from `futures` - he thing is that you can return any future from the RPC call.
This particular example is returning a `Future` that is created from a sync `Result`, and that's just the name of the type for this particular future.

Returning `Box<dyn Future>` is simply the easiest way, especially if you use any future combinators and you can't name the type (or it's just too long).

Feel free to update the documentation and return something else or add some other methods in a way that would make that clear for you.
