### ISSUE TITLE
Consider supporting subscriptions with the same names

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/jsonrpc#511]
Take `substrate` case for example:
```
Subscribe: author_submitAndWatchExtrinsic
Subscribe: author_watchExtrinsic

Subscription: author_extrinsicUpdate

Unsubscribe: author_unwatchExtrinsic
```
Both methods open the `author_extrinsicUpdate` subscription, and you can unsubscribe from them with the same method, but they take different parameters when the subscription is created.

I guess it's supported without `derive`, we just need to figure out how to do it with.

**Comment by NikVolf** [comment]
implemented in #512
