### ISSUE TITLE
generating rpc methods for mutable &self references

### ISSUE THREAD

**Issue by nuliknol** [paritytech/jsonrpc#528]
It seems that generating RPC methods for mutable `self` references is not supported.

This is the function signature I have:

```
#[rpc]
pub trait MyApi {
    /// RPC Metadata
    type Metadata;

    /// Submit a signed transaction using raw hex as input
    #[rpc(name = "sendtransaction")]
    fn send_transaction(&mut self, hex: String) -> Result<String>;
```
Note the `&mut self` . I need &self to be mutable because I am modifying the data.
However this code doesn't compile, this is what I get:

```
error[E0605]: non-primitive cast: `for<'r> fn(&'r mut Self, std::string::String) -> std::result::Result<std::string::String, error::Error> {<Self as api::rpc_impl_MyApi::gen_server::MyApi>::send_transaction}` as `for<'r> fn(&'r Self, std::string::String) -> std::result::Result<std::string::String, error::Error>`
 --> myproject/rpc/src/api.rs:9:1
  |
9 | #[rpc]
  | ^^^^^^
  |

```
I have searched through the source code of jsonrpc and didn't find any `&mut self` example. So, how do you guys use this crate when you need to generate rpc functions for mutable objects?

**Comment by tomusdrw** [comment]
The server can be used from multiple threads, so the methods need to be thread-safe. Please use a `Mutex` or `RwLock` if you need to access/alter shared state.
