### ISSUE TITLE
Support for by-name parameters in #[rpc(client)] macro

### ISSUE THREAD

**Issue by willemolding** [paritytech/jsonrpc#540]
The RPC server I wish to communicate with only supports by-name parameters. I was hoping to build a nice typed adapter using the #[rpc(client)] macro but it appears this only supports by-position params. And in fact the `call_method` for `TypedClient` seems to ignore the fact that by-name calling is possible at all https://github.com/paritytech/jsonrpc/blob/ef44a62c543fd969dd5bedf5a4ece3f3814bb111/core-client/transports/src/lib.rs#L303

It seems like it would be pretty easy to add support for this with a switch in the proc macro to select the calling type. Is there a good reason I am missing as to why it hasn't been done this way? If not I'll submit a PR

**Comment by tomusdrw** [comment]
cc @ascjones do you know any limitations?

**Comment by ascjones** [comment]
I think this was just because IIRC our server implementation only supports positional params, and this was "good enough" for our initial use cases.

But can't think of any reason why the client couldn't/shouldn't implement this for wider compatibility.
