### ISSUE TITLE
Add "Accept" Header for http transport for client

### ISSUE THREAD

**Issue by yinhu-prismalab** [paritytech/jsonrpc#542]
I am not sure about whether it should be there or not by protocol/standard but it seems some existing libs for other language (e.g. http-jsonrpc-server for nodejs) requires "application/json" for "Accept" header alone with the "Content-type" the current implementation have.

It would be nice to have a way to  config the headers not only for working with other libs but also exiting old systems that one cannot modify.

**Comment by tomusdrw** [comment]
I believe we do allow `Accept` header to be sent on the requests, do you mean it should be included in the response as well? This header is request-only, I don't think that would work.

Could you point me to some examples what kind of requests/responses the client library sends/expects?

**Comment by yinhu-prismalab** [comment]
I mean the client part: jsonrpc/core-client/transports/src/transports/http.rs , it seems only content-type is set. My current code is based on an older version of this crate, I haven't tried latest version yet. But the code on github seems the still the same.

**Comment by tomusdrw** [comment]
@yinhu-prismalab Oh, I see. Yeah, we should definitely send `Accept` header unconditionally in the client. Feel free to submit a PR, happy to review it.

**Comment by yinhu-prismalab** [comment]
Created PR #544 . 
Simply  added a new header in the requests.
Please let me know if I should modify somewhere else as well.

**Comment by tomusdrw** [comment]
Resolved via #544
