### ISSUE TITLE
eth_sendTransaction for help!

### ISSUE THREAD

**Issue by lz931585538** [paritytech/jsonrpc#555]
Hello，I want to find a function named "eth_sendTransaction" in the standard library but I can't find it.
Would you mind telling me where the function is?

Thank you !

**Comment by tomusdrw** [comment]
This repo only contains the code for the library used to implement the RPC. There is nothing ethereum specific here.

Please either take a look at:
- Server Side: https://github.com/openethereum/openethereum
- Client Side: https://github.com/tomusdrw/rust-web3
