### ISSUE TITLE
Reflecting tokio-service -> tower-service dependency change?

### ISSUE THREAD

**Issue by jnpkrn** [paritytech/jsonrpc#562]
[originally, I thought that `tokio-service` is not amongst dependencies,
the point was that I've made said rename locally and forgot about actual
usages, and only later figured out what's going on]

Is this upstream rename/migration of that project suitable for being reflected?

See https://github.com/tokio-rs/tokio-service/pull/32

There are some changes in API as well, sadly, e.g.:

```
error[E0107]: wrong number of type arguments: expected 1, found 0
  --> tcp/src/service.rs:24:37
   |
24 | impl<M: Metadata, S: Middleware<M>> tower_service::Service for Service<M, S> {
   |                                     ^^^^^^^^^^^^^^^^^^^^^^ expected 1 type argument
```

**Comment by tomusdrw** [comment]
The whole library for now is using `futures=0.1` and that means `tokio-service`. See #485 for more details.
