### ISSUE TITLE
jsonrpc-core-client: Get specific client impl from connect method

### ISSUE THREAD

**Issue by SirWindfield** [paritytech/jsonrpc#563]
Hey!

I have a common crate in my project that defines the Rpc methods using the `derive` proc-macro. My client and my server both depend on the crate. The server implements the trait and provides a server over `ipc`.

I now want my client to be able to connect to it. I added the `ipc` feature to the `jsonrpc-core-client` crate but I can't figure out how to get `dyn Rpc` as my return type and not a `RawClient` (as in the example section of the client code).

On a side note, does `IPC` always work over files? Or can I also pass down pipe names?

**Comment by tomusdrw** [comment]
> On a side note, does IPC always work over files? Or can I also pass down pipe names?

Filename on *nix and pipe names on Windows (but I'm not sure if client supports windows as well).

> I can't figure out how to get dyn Rpc as my return type and not a RawClient

I'm not sure I fully understand. You can't get `dyn Rpc` return type, it has to be a concrete object. The return type of `connect` method just requires anything that implements `From<RpcChannel>`. If your client code is generated, it should be available in `gen_client` module, so you should be able to do something like that:
```
	let (client, server) = ipc::connect::<gen_client::Rpc, _, _>(...);
	client.add(5, 6) // or any method that is defined in `Rpc` trait.
```

**Comment by SirWindfield** [comment]
Thank you very much, that helped me out :)

Generally speaking, I saw that some people are working on `jsonrpsee`. Is it better to open PRs in this repo or the "new" one? I wanted to add support for named pipes for both unix and windows :)

**Comment by tomusdrw** [comment]
Afaict named pipes (on windows) should already be supported, since we are using https://github.com/NikVolf/parity-tokio-ipc

`jsonrpsee` is a new (but still not production-ready) approach, with the main advantage being full rewrite with async-await in mind. If you need something more battle-tested I'd suggest `jsonrpc`.

Can I close the issue? Or is there anything that I missed and is still not addressed?

**Comment by SirWindfield** [comment]
Everything's good!
