### ISSUE TITLE
README use of FutureResult is out of date

### ISSUE THREAD

**Issue by jbaublitz** [paritytech/jsonrpc#596]
I tried using `FutureResult` as specified in the README when trying to prototype a derived interface, but the `jsonrpc_core::Error` type cannot be used in `FutureResult` as suggested by the README. I've dug into the code a little bit more and it appears that it is expecting the second type parameter to `FutureResult` to be a `Future` which `jsonrpc_core::Error` is not. Would you be able to update the README or provide a suggestion for how to work around this?

**Comment by niklasad1** [comment]
Which version/branch are you using?

I think https://github.com/paritytech/jsonrpc/pull/565 updated to `futures v0.3` and the README might be outdated.

//cc @tomusdrw

**Comment by jbaublitz** [comment]
I'm using the latest released version which appears to be `15.1.0`. I've checked both that branch and the master branch to see if there was a difference, but they both appear to be out of date. I tried playing around with this a little bit, but it appears that the derive macro only accepts the `jsonrpc_core::Result` or `jsonrpc_core::FutureResult` type as a return type for the trait methods.

**Comment by tomusdrw** [comment]
@jbaublitz `master` example indeed won't work with `15.1.0`. Can you post a code sample which you have problem with and the compiler error?

This code uses `15.1.x`:
https://github.com/paritytech/substrate/blob/53ab714d03babdcb5538232a7c36ca89266180e6/client/rpc-api/src/state/mod.rs#L43

`FutureResult` is defined like so:
https://github.com/paritytech/substrate/blob/53ab714d03babdcb5538232a7c36ca89266180e6/client/rpc-api/src/state/error.rs#L28

**Comment by jbaublitz** [comment]
This is no longer an issue for me. Closing.
