### ISSUE TITLE
jsonrpc-ws-server buffer configuration knobs are not released

### ISSUE THREAD

**Issue by t-nelson** [paritytech/jsonrpc#599]
It would be great to have access to the buffer configuration knobs added to `jsonrpc-ws-server` in #594

Any chance a new release could be cut with it included? :pray:

**Comment by tomusdrw** [comment]
@t-nelson First release of 16.x series should be out now :tada: .

**Comment by t-nelson** [comment]
Thanks @tomusdrw !
