### ISSUE TITLE
Cut a new release with Tokio 0.2 support

### ISSUE THREAD

**Issue by Xanewok** [paritytech/jsonrpc#607]
Now that #603 is merged, it'd be good to cut a major release containing it. Because the Tokio ecosystem is currently somewhat split between Tokio 0.1, 0.2, and 0.3/1.0, I believe it'd be beneficial to cut a release for projects that are still stuck in the 0.2; either because it's a non-trivial upgrade or because their dependencies still rely on the 0.2 version.

Once we release that, we can safely upgrade to Tokio 1.0 and get rid of some old deps, e.g. #575.

**Comment by tomusdrw** [comment]
v17.0 is out.
