### ISSUE TITLE
jsonrpc server can send notifcation message to client?

### ISSUE THREAD

**Issue by ahczbhht1989** [paritytech/jsonrpc#635]
jsonrpc server can send notifcation message to client,  I want to call raw method,
such as send_rpc_notification to client，can do this?

**Comment by tomusdrw** [comment]
It's only possible through subscription mechanism. Please take a look at examples [here](https://github.com/paritytech/jsonrpc/blob/master/pubsub/more-examples/examples/pubsub_ws.rs#L60) or in the Open Ethereum / Substrate usage.
