### ISSUE TITLE
Fail to enable `http` feature of `jsonrpc-core-client`

### ISSUE THREAD

**Issue by yvan-sraka** [paritytech/jsonrpc#636]
I enabled `http` feature of `jsonrpc-core-client` and I got this issue:

```
error[E0599]: no function or associated item named `new` found for struct `Client` in the current scope
  --> /home/yvan/.cargo/registry/src/github.com-1ecc6299db9ec823/jsonrpc-client-transports-18.0.0/src/transports/http.rs:32:23
   |
32 |     let client = Client::new();
   |                          ^^^ function or associated item not found in `Client<_, _>`
```

This occurs in an empty `fn main() {}` program, just by adding `jsonrpc-core-client = { version = "18.0.0", features = ["http"] }` line in `Cargo.toml` (you can found the full demo program here: https://github.com/yvan-sraka/jsonrpc-client-http-demo).

Due to the lack of documentation, I couldn’t determine if this behavior is normal (and I just didn’t find out yet how to use the feature) or if it shouldn’t fail this way?

I was using Rust nightly and I test that the issue didn’t occurs with previous version `17.0.0` of `jsonrpc-core-client` crate …

**Comment by niklasad1** [comment]
hrm, that should work the `http feature` should enable `hyper` and the error is that `hyper::client::Client::new()`couldn't be found but maybe we need type hints for it @tomusdrw?!

Meanwhile I think it will work if you enable the `tls`feature too: 
`jsonrpc-core-client = { version = "18.0.0", features = ["http", "tls"] }`
