### ISSUE TITLE
Use procedural macros

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/jsonrpc#66]
Replace `build_rpc_trait` macro with custom derive since it starts to get unmaintanable.

**Comment by ivanovaleksey** [comment]
Hello @tomusdrw, I would like to figure out how `build_rpc_trait` works and I am interested in this task.
Is it still actual? I could try to help although for now I got very few knowledge.

**Comment by tomusdrw** [comment]
Yes, it's not super urgent, but probably worth looking into. Let me know if I can help you with that (ping me on gitter).
