### ISSUE TITLE
Importing from cargo gives trait bound errors

### ISSUE THREAD

**Issue by kvsari** [paritytech/jsonrpc#80]
Creating a new project and doing a cut-n-paste of the code in [example server.rs](https://github.com/paritytech/jsonrpc/blob/master/http/examples/server.rs) fails to compile with error; [error.txt](https://github.com/paritytech/jsonrpc/files/853227/error.txt)

The only way to fix this is to clone the entire jsonrpc repository and then set Cargo.toml to path into the cloned projects subdirectories for core and http. Setting up Cargo the way as instructed in the documentation doesn't work.

I want to be able to just get the jsonrpc-core and jsonrpc-http-server crates from crates.io in my Cargo.toml.

**Comment by debris** [comment]
Thanks for report! I will work on it

**Comment by tomusdrw** [comment]
Documentation fixed in #93 another solution proposed in #84
