### ISSUE TITLE
jsonrpc-core should support io::Read and io::Write

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/jsonrpc#82]
Instead of allocating a String and then passing it to `jsonrpc-core` it should be possible to just pass instance of `io::Read` and `io::Write` (later). See:

https://docs.rs/serde_json/0.9.5/serde_json/fn.from_reader.html
https://docs.rs/serde_json/0.9.5/serde_json/fn.to_writer.html

**Comment by debris** [comment]
yes, but I'm afraid it won't work for network requests, cause `io::Read`, `io::Write` may return `WouldBlock` error

What we need is serde using futures internally

**Comment by tomusdrw** [comment]
I think it would be possible to create a buffered reader that addresses this issue. You just need to make sure that BufferedReader polling occurs in the event loop, and `serde_json::from_reader` is blocking some other thread.
Although it indeed seems a bit complicated.

**Comment by mmacedoeu** [comment]
Hey guys maybe you need tokio_io::{AsyncRead, AsyncWrite}
https://github.com/tokio-rs/tokio-io/blob/master/src/lib.rs#L94
https://github.com/hyperium/hyper/blob/master/src/server/mod.rs#L270

**Comment by NikVolf** [comment]
@mmacedoeu yep but serde does not use it
and if it were, it would have to return futures instead of instant result on such (de)serialization requests

**Comment by mmacedoeu** [comment]
Now I see :)
Maybe some could wrap serde into a CpuFuture:
https://github.com/alexcrichton/futures-rs/blob/master/futures-cpupool/src/lib.rs#L114

or try FramedRead, FramedWrite:
https://github.com/carllerche/tokio-serde/blob/master/src/lib.rs#L223

**Comment by tomusdrw** [comment]
Closing since it seems unrealistic.
