### ISSUE TITLE
File descriptor transport server

### ISSUE THREAD

**Issue by LukeSkyw** [paritytech/jsonrpc#87]
Would there be an interest to implement a file descriptor 'transport server' ?
So you could just use stdin to send json command, and pipe programs together.
Useful for test purposes as well.

**Comment by tomusdrw** [comment]
Pretty cool idea. Help appreciated! :+1: 

@adrianbrink interested? :)

**Comment by cmichi** [comment]
I think this issue can be closed together with #194 since #299 was merged.

**Comment by tomusdrw** [comment]
Yup, thanks! Closed via #299
