### ISSUE TITLE
Macros framework should allow implementations to choose return type

### ISSUE THREAD

**Issue by rphmeier** [paritytech/jsonrpc#9]
Right now it's enforced trait-wide which means that every implementation is limited by the least-capable one.

**Comment by tomusdrw** [comment]
The discussed idea was to use associated types:

```rust
build_rpc_trait! {
 trait Rpc {
   fn some_method(&self) -> Result<String, Error>;
   fn some_other_method(&self) -> BoxFuture<String, Error>;
 }
}

struct RpcDefault;
impl Rpc for RpcDefault {
   fn some_method(&self) -> Result<String, Error> { unimplemented!() }
   fn some_other_method(&self) -> BoxFuture<String, Error>  { unimplemented!() }
}

struct RpcAsync;
impl Rpc For RpcAsync {
  type some_method = BoxFuture<String, Error>;

   fn some_method(&self) -> BoxFuture<String, Error> { unimplemented!() }
   fn some_other_method(&self) -> BoxFuture<String, Error>  { unimplemented!() }
}
```

**Comment by rphmeier** [comment]
This is fine but the naming convention is pretty ugly (and rustc is bound to complain; users will need to use some custom lint settings).
We could require that the mandatory `#[rpc]` annotation be formatted like this: 
`#[rpc(name="rpc_nameHere", return=NameHere)]`
fn name_here(&self) -> Result<Foo, Error>;

**Comment by tomusdrw** [comment]
Renamed the issue to support arbitrary return types with `Into<BoxFuture<String, Error>>` bounds.

We could then provide a special `jsonrpc_core::Result` type with proper `From<Result>` and `Into<BoxFuture>` implementation

**Comment by tomusdrw** [comment]
The core part of the code already have relaxed requirements and recent switch to proc-macro should allow for more free form types to be returned (for instance an enum encapsulating possible results that implements `Into<BoxFuture>`)
