### ISSUE TITLE
The example in the readme doesn't compile

### ISSUE THREAD

**Issue by eriklarko** [paritytech/jsonrpc#92]
I might be totally noobish, but I can't get the example code to compile :(
I put the exact code I'm compiling in https://github.com/eriklarko/jsonrpc-recreate

**Comment by tomusdrw** [comment]
Unfortunatelly you need to reference both `jsonrpc-core` and `jsonrpc-http-server` from the repo to make it work. We have another issue #84 that can solve that issue.

`jsonrpc-http-server` contains some dependencies that are not released to `crates.io` yet, so it cannot be released to creates itself.
We hope to rewrite `jsonrpc-http-server` to `hyper`, when it's future-based version is finished, so the situation is only temporary.

I've made a PR to your repo to fix it:) https://github.com/eriklarko/jsonrpc-recreate/pull/1

**Comment by eriklarko** [comment]
:D Thanks for the amazing help! The PR works great. And thanks for a sweet library!
